language: elixir
services:
  - postgresql
addons:
  postgresql: "10"
elixir:
  - '1.8.0'
otp_release:
  - '21.0'
env:
  - MIX_ENV=test CORTEX_ENABLED=false
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile --warnings-as-errors
  - mix do ecto.create, ecto.migrate
script:
  - mix test
  - mix credo -a
  - mix format --check-formatted
